#! /bin/sh
### BEGIN INIT INFO
# Provides:          httpd
# Required-Start:    $network
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: Start busybox httpd server
# Description: Start busybox httpd server
#
### END INIT INFO
### Copyright(c) 2011 OpenDomo Services SL. Licensed under GPL v3 or later


. /lib/init/vars.sh
. /lib/lsb/init-functions

HTTPD_CONFIG="/etc/httpd.conf"
WEB_SERVICE="/var/www"
PID="/var/opendomo/run/httpd.pid"
HTTPD_OPTS="httpd -c $HTTPD_CONFIG -h $WEB_SERVICE"

do_start () {
	# Only start server without lighttpd
	test -x /usr/sbin/lighttpd && exit 0

	# Starting server
	log_action_begin_msg "Starting HTTPD busybox server"
	touch $PID
	start-stop-daemon --start --quiet --oknodo --pidfile $PID --exec /bin/busybox -- $HTTPD_OPTS
	log_action_end_msg $?
}

do_stop () {
	log_action_begin_msg "Stoping HTTPD busybox server"
	start-stop-daemon --stop --quiet --oknodo --signal TERM --exec /bin/busybox --pidfile $PID
	killall -9 busybox 2>/dev/null
	log_action_end_msg $?
}

do_status () {
	log_daemon_msg "HTTPD busybox daemon"
	if test -f "$PID"; then
		echo " (Is running)"
	else
		echo " (Is not running)"
	fi
}

case "$1" in
  start|"")
	do_start
        ;;
  restart|reload|force-reload)
	do_stop
	do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: httpd [start|stop|restart|status]"
        exit 1
        ;;
esac

:
