#!/bin/sh
#desc: Save changes permanently

# USAGE:
#   mkrootfs              Save changes
#   mkrootfs    reboot    Save changes and reboot system
#   mkrootfs    restore   Restore default system

# Variables
IMAGESDIR="/boot/images"
ROOTIMAGE="$IMAGESDIR/rootfs.img"
MOUNTDIR="/mnt/rootfs-rw"
TMPFSDIR="/mnt/tmpfs"

SYNCOPTS="--quiet --archive --exclude-from=/etc/mkrootfs.excludes"
TEMPFILE="/var/opendomo/tmp/mkrootfs.tmp"

# Checking state and image mount
if grep -c1 aufs=no "/proc/cmdline" &>/dev/null; then
    echo "#ERRO System is in read-write mode"
    echo
    exit 0

elif ! test -d $IMAGESDIR; then
    echo "#ERRO System device is not mounted, the configuration can't be saved"
    echo
    exit 1

elif [ "$1" = "restore" ]; then
    # Entering in busy system state
    echo "Restoring system" > $SYSSTATE
    #TODO: New restore system required

else
    # Check filesystems before mount
    mount | grep $MOUNTDIR  &>/dev/null && umount -f $MOUNTDIR
    fsck.ext2 -y $ROOTIMAGE &>/dev/null

    # Mount changes image in rw and check tmpfs
    mkdir -p $MOUNTDIR
    test -d $TMPFSDIR || exit 1
    mount $ROOTIMAGE $MOUNTDIR || exit 1

    # Entering in busy system state
    # TODO: System busy state is will be in jsaon format

    # Copy new files in image
    echo "#LOADING Save system configuration (please wait) ..."
    echo
    rsync $SYNCOPTS $TMPFSDIR/ $MOUNTDIR/

    # Delete missing files in image
    find $TMPFSDIR -name ".wh.*" -not -name ".wh..*" | sed -e 's/tmpfs/rootfs-rw/' -e 's/.wh.//' > $TEMPFILE
    for file in `cat $TEMPFILE`; do
        rm -r "$file" 2>/dev/null
    done
    rm $TEMPFILE

    # Unmount and check image
    while ! umount $MOUNTDIR; do
        sleep 1
    done
    rmdir $MOUNTDIR 2>/dev/null
    fsck.ext2 -y $ROOTIMAGE &>/dev/null
fi

# Check reboot system warrant
if [ "$1" == "reboot" ]; then
    echo "#> Configuration saved"
    echo "#INFO Your configuration was saved, rebooting system ..."
    echo
    shutdown -r now
else
    echo "#> Configuration saved"
    echo "#INFO Your configuration was saved"
    echo
fi
