#! /bin/sh

BUSYBOX_USER_CMD="ar bunzip2 bzip2 bzcat cal dc freeramdisk ftpget ftpput ifconfig less microcom ping ping6 rdate realpath tree telnet tftp traceroute traceroute6 uncompress unexpand unix2dos unzip uuencode vi"
BUSYBOX_ADMI_CMD="arping hexdump httpd ipcalc logread mdev vconfig watchdog"

echo "Creating busybox symbolic link ..."

for cmd in $BUSYBOX_ADMI_CMD; do
	ln -fs /bin/busybox "/usr/local/sbin/$cmd" 2>/dev/null
done
for cmd in $BUSYBOX_USER_CMD; do
	ln -fs /bin/busybox "/usr/local/bin/$cmd" 2>/dev/null
done

echo "Configuring opendomo folders and files ..."
ln -fs /usr/local/opendomo/services/syscript/logEvent.sh /bin/logevent

echo "Configuring opendomo services ..."
insserv uid  2>/dev/null
insserv odloadconf  2>/dev/null
insserv odfirstinit.sh  2>/dev/null
insserv odchstates.sh  2>/dev/null
insserv keymap 2>/dev/null
insserv diskmanager 2>/dev/null
insserv opendomo-apt 2>/dev/null
insserv ntpdate 2>/dev/null
