#!/bin/sh
#desc: Make opendomo squash filesystems

# Variables
IMAGESDIR="/mnt/system/images"
MOUNTDIR="/run/mounts/changerw"
CHANGEDIR="/run/mounts/change"
TEMPFSDIR="/run/mounts/tmpfs"
SYNCOPTS="--quiet --archive --delete --exclude-from=/etc/mkrootfs.excludes"

# Checks
fi

if ! test -d $IMAGESDIR; then
	echo "#ERR: System device is not mounted"
	exit 1
fi

# Select image
if test -z $1; then
	echo "USAGE: mkrootfs [ custom / default ]"
	exit 1
elif [ "$2" = "custom" ]; then
	IMAGE="$IMAGESDIR/ctchange.img"
elif [ "$2" = "default" ]; then
	IMAGE="$IMAGESDIR/dfchange.img"
else
	echo "#ERR: Selected image is not valid"
	exit 1
fi

# Mounting image
mkdir -p $MOUNTDIR
mount $IMAGE $MOUNTDIR || exit 1

# Creating image
echo -n "#INF: Creating rootfs, please wait "
if
	rsync $SYNCOPTS $TEMPFSDIR $MOUNTDIR
then
	echo "   (done)"
else
	echo "   (error)"
fi
