#!/bin/sh
### BEGIN INIT INFO
# Provides:          odhal
# Required-Start:    $network
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: Control board drivers
# Description:       Daemon for manage microcontrollers
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

CFGPATH="/etc/opendomo/control"
CTRLPATH="/var/opendomo/control"
PID="/var/opendomo/run/odcontrol.pid"

do_start () {
	# Load drivers configuration
	for i in $CFGPATH/*.conf; do
		if test -f $i; then
			# Load configuration
			. $i

			# Start all configured drivers
			BINARY="/usr/bin/$driver"
			ARGS="-d $device -p $dirname -r refresh $params"
			if test -x "$BINARY"; then
				$BINARY $ARGS >>/var/opendomo/log/odhal_$dirname.log 2>/var/opendomo/log/odhal_$dirname.err &
				echo -n " ($dirname)"
			else
				echo -n " ($dirname failed)"
			fi
		fi
	done

	echo "" >$PID
}

do_stop () {
	for i in $CFGPATH/*.conf; do
		if test -f $i; then
			# Loading drivers
			. $i
			# Kill drivers
			killall -TERM $driver 2>/dev/null
			echo -n " ($dirname)"

			# Remove directory
			rm -fr $CTRLPATH/$dirname
		fi

	done
	chmod +w -R $CTRLPATH/* 2>/dev/null
	rm -fr $CTRLPATH/ODC*

	rm /var/opendomo/domino_devices.conf 2>/dev/null
	rm -fr $PID
}


case "$1" in
	start)
		log_daemon_msg "Starting opendomo controllers"
		if test -f $PID; then
			echo -n " (already started)"
			log_end_msg 2
		else
			do_start
		fi
		log_end_msg $?
	;;
	stop)
		log_daemon_msg "Stopping controllers"
		do_stop
		log_end_msg $?
	;;
	status)
		if test -f $PID; then
			echo "The service is running"
			exit 0
		else
			echo "Service not started"
			exit 1
		fi
	;;
	restart)
		log_daemon_msg "Reloading controllers..."
		do_stop
		do_start
		log_end_msg $?
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
esac

:
