#! /bin/sh
### BEGIN INIT INFO
# Provides:          odconf
# Required-Start:    udev
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Load opendomo configuration files
# Description:       Load opendomo configuration files
#
### END INIT INFO
### Copyright(c) 2011 OpenDomo Services SL. Licensed under GPL v3 or later


. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start () {
	DEFCONF=/mnt/odconf/sysconf/defconf.tar.gz
	CSTCONF=/mnt/odconf/sysconf/cstconf.tar.gz
	LOGFILE="/var/opendomo/log/loadcfg.log"

	# Make all opendomo dirs
	mkdir -p /var/opendomo/tmp /var/opendomo/log /var/opendomo/run /var/opendomo/cgiroot /var/opendomo/control
	mkdir -p /etc/opendomo /usr/local/opendomo/
	touch $LOGFILE

	# Selecting config and extract
	if test -f $CSTCONF; then
		log_action_begin_msg "Updating opendomo configuration files (custom)"
		tar xfzp $CSTCONF -C / 2>$LOGFILE
		log_action_end_msg $?
	else
		if test -f $DEFCONF; then
			log_action_begin_msg "Updating opendomo configuration files (default)"
			tar xfzp $DEFCONF -C / 2>$LOGFILE
			log_action_end_msg $?
		else
			log_warning_msg "No opendomo configuration file found!"
		fi
	fi

	# Fix perms
	chown root:root /etc
	chmod ugo+rx /etc

	chown -R admin:admin /usr/local/opendomo
	chown -R admin:admin /var/opendomo
	chown -R admin:admin /etc/opendomo
	chmod -R 744 /usr/local/opendomo
	chmod -R 744 /var/opendomo
	chmod -R 744 /etc/opendomo

	# Create wrapper scripts
	log_action_begin_msg "Creating opendomo wrapper scripts"
	su -c /usr/local/bin/createwrappers.sh admin 2>$LOGFILE
	log_action_end_msg $?
}

case "$1" in
  start|"")
	do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
   status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
 stop)
        # No-op
        ;;
  *)
        echo "Usage: odloadconf [start]" >&2
        exit 3
        ;;
esac

:
