#! /bin/sh
### BEGIN INIT INFO
# Provides:          opendomo-apt
# Required-Start:    $network
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Opendomo apt daemon
# Description:       Install opendomo plugins, deps and update system daemon
#
### END INIT INFO
### Copyright(c) 2014 OpenDomo Services SL. Licensed under GPL v3 or later

. /lib/init/vars.sh
. /lib/lsb/init-functions

PIDFILE="/var/opendomo/run/opendomo-apt.pid"
LOGFILE="/var/opendomo/log/opendomo-apt.log"
ERRFILE="/var/opendomo/log/opendomo-apt-error"

do_start () {
	log_action_begin_msg "Starting opendomo apt daemon"
	echo "Waiting" > $PIDFILE
	/usr/local/sbin/opendomo-apt >$LOGFILE 2>$ERRFILE &
	log_action_end_msg $?
}

do_stop () {
	log_action_begin_msg "Stoping opendomo apt daemon"
	rm $PIDFILE 2>/dev/null
	killall -TERM opendomo-apt >/dev/null 2>/dev/null
	log_action_end_msg $?
}

do_status () {
	if test -f $PIDFILE; then
		echo "$basename $0 is running"
		exit 0
	else
		eche "$basename $0 is not running"
		exit 1
	fi
}

case "$1" in
  start|"")
	do_start
        ;;
  restart|reload|force-reload)
	do_start
	do_stop
        exit 3
        ;;
  stop)
	do_stop
        exit 3
	;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: opendomo-apt [start|stop|restart|status]" >&2
        exit 3
        ;;
esac

:
