#! /bin/sh
### BEGIN INIT INFO
# Provides:          uid
# Required-Start:    $network
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Set uid and uid based hostname
# Description:       Read network configuration, select hostname and
#		     UID opendomo configuration
### END INIT INFO

### Copyright(c) 2014 OpenDomo Services SL. Licensed under GPL v3 or later


. /lib/init/vars.sh
. /lib/lsb/init-functions

UIDFILE="/etc/opendomo/uid"
HOSTSFILE="/etc/hosts"

do_start () {

	if ! test -f "$UIDFILE"
	then
		/sbin/ifconfig eth0 | grep HWaddr | cut -c 39-55 | sed -e 's/://g' > $UIDFILE
		chown 1000:1000 $UIDFILE
	fi

	# Updating hosts files
	OTHERHOSTS=`cat $HOSTSFILE | grep -v $HOSTNAME`
	HOSTNAME=`cat /etc/hostname`
	echo "127.0.0.1	$HOSTNAME" 	 >$HOSTSFILE
	echo "$OTHERHOSTS"		>>$HOSTSFILE
}

do_status () {
	if test -f "$UIDFILE"; then
                return 0
        else
                return 4
        fi
}

case "$1" in
  start|"")
	log_action_begin_msg "Creating OpendomoOS UID"
	do_start
	log_action_end_msg $?
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: uid [start]" >&2
        exit 3
        ;;
esac

:
