#!/bin/bash

FUNCDIR=files/scripts/
source $FUNCDIR/fct_vars

download_target() {
    if ! test -f $TEMPDIR/$ROOTFSPKG; then
        if wget -nc -q --directory-prefix=$TEMPDIR --no-check-certificate $ROOTFSURL; then
	    echo -e "(${DONE}done${NORL})"
        else
            echo -e "(${ERRO}failed${NORL})"
            exit 1
        fi
    else
        echo -e "(${OMIT}omited${NORL})"
    fi
}

extract_target() {
    # Clean old image and create folders
    rm -r $IMAGESDIR 2>/dev/null
    mkdir -p $IMAGESDIR

    # Extract rootfs image
    if ! test -d $ROOTFSDIR; then
        cd $TEMPDIR
        if tar xfJp $ROOTFSPKG 2>/dev/null; then
            echo -e "(${DONE}done${NORL})"
        else
            echo -e "(${ERRO}failed${NORL})"
            exit 1
        fi
        cd ..
    else
        echo -e "(${OMIT}omited${NORL})"
    fi

    # Copy qemu static emulator to target (only in arm)
    [ "$ARCH" = "arm" ] && cp /usr/bin/qemu-arm-static $ROOTFSDIR/usr/bin 2>/dev/null
}

build_rootstrap() {
    # Copy initrd to create rootstrap
    if ! test -d $ROOTSTDIR; then
        cp -rp $ROOTFSDIR $ROOTSTDIR
        rm -fr $ROOTSTDIR/etc/resolv.conf
        cp /etc/resolv.conf $ROOTSTDIR/etc/

        # Update rootstrap apt sources
        if $CHROOT $ROOTSTDIR /bin/bash -c "apt-get update" &>> $LOGSDIR/rootstrap.$ARCH.log; then
            echo -ne "(${DONE}sources${NORL}) "
        else
            echo -ne "(${ERRO}sources${NORL}) "
        fi
        if $CHROOT $ROOTSTDIR /bin/bash -c "LC_ALL=C LANGUAGE=C LANG=C DEBIAN_FRONTEND=noninteractive \
            apt-get --force-yes -yq install $RPKGS" &>> $LOGSDIR/rootstrap.$ARCH.log; then
            echo -e "(${DONE}install${NORL}) "
        else
            echo -e "(${DONE}install${NORL}) "
        fi
    else
        echo -e "(${OMIT}omited${NORL})"
    fi
}

create_packages() {
    # Clean old packages
    rm -r $ROOTSTDIR/tmp/* 2>/dev/null

    # Copy package into rootstrap and build
    cp -r $ODPKGDIR/$ODPKG $ROOTSTDIR/tmp/ 2>/dev/null
    if $CHROOT "$ROOTSTDIR" /bin/bash -c "cd /tmp/$ODPKG && dpkg-buildpackage 2>/dev/null >/dev/null" &>/dev/null; then
        echo -ne "(${DONE}$pkg${NORL}) "
    else
        echo -ne "(${ERRO}$pkg${NORL}) "
    fi

    # Copy packages to export directory
    cp $ROOTSTDIR/tmp/$ODPCKG_*.deb $EXPORTDIR/ 2>/dev/null
    chown `users | cut -f1 -d" "` $EXPORTDIR/*.deb &>/dev/null
    echo
}

install_packages() {
    # Mount dev device
    mount --bind /dev $ROOTFSDIR/dev 2>/dev/null

    # Select opendomo packages to install
    if ls $ROOTSTDIR/tmp/*.deb &>/dev/null; then
        cp $ROOTSTDIR/tmp/*.deb $ROOTFSDIR/tmp/ 2>/dev/null
    else
        # Download packages
        wget -nc -q --directory-prefix=$ROOTFSDIR/tmp --no-check-certificate $ODPKGURLS
    fi

    # Install opendomo packages
    if $CHROOT "$ROOTFSDIR" /bin/bash -c "dpkg -i tmp/$ODPKG*" &>/dev/null; then
        echo -ne "(${DONE}$NAME${NORL}) "
    else
        echo -ne "(${ERRO}$NAME${NORL}) "
    fi
    echo

    # Rebuild apt database (just in case), clean packages and umount dev
    $CHROOT "$ROOTFSDIR" /bin/bash -c "apt-get -f install" &>/dev/null
    rm $ROOTFSDIR/tmp/*.deb   2>/dev/null
    rm -r $ROOTSTDIR/tmp/*    2>/dev/null
    umount -fl $ROOTFSDIR/dev 2>/dev/null
}
