#!/bin/bash

FUNCDIR=files/scripts/
source $FUNCDIR/fct_vars
source $FUNCDIR/fct_build
source $FUNCDIR/fct_export
mkdir -p $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR
chown $USER $EXPORTDIR $TEMPDIR $LOGSDIR $IMAGESDIR $MOUNTDIR

case $1 in
    update )
        echo -e "########## Updating OpenDomoOS SDK ##########"
        echo
        echo -e "[${INFO} 1/1 ${NORL}] Updating SDK ..."
        git pull &> $LOGSDIR/update.log
        echo
    ;;
    clean )
        echo -e "########## Cleaning OpenDomoOS SDK ##########"
        echo
        echo -e "[${INFO} 1/1 ${NORL}] Cleaning SDK ..."
	rm -r $TEMPDIR/* &>/dev/null
        echo
    ;;
    build )
        echo -e "########## Building OpenDomoOS packages for $2 ##########"
        echo
        echo -ne "[${INFO} 1/5 ${NORL}] Downloading rootfs package ...              "
        download_target
        echo -ne "[${INFO} 2/5 ${NORL}] Extract rootfs package ...                  "
        extract_target
        echo -ne "[${INFO} 3/5 ${NORL}] Build rootstrap image ...                   "
        build_rootstrap
        echo -ne "[${INFO} 4/5 ${NORL}] Creating opendomo packages ...              "
        create_packages
        echo -ne "[${INFO} 5/5 ${NORL}] Install opendomo packages in rootfs ...     "
        install_packages
        echo
    ;;
    assemble )
        echo -e "########## Building OpenDomoOS for $2 ##########"
        echo
        echo -ne "[${INFO} 1/3 ${NORL}] Downloading rootfs package ...           "
        download_target
        echo -ne "[${INFO} 2/3 ${NORL}] Extract rootfs package ...               "
        extract_target
        echo -ne "[${INFO} 3/3 ${NORL}] Install opendomo packages in rootfs ...  "
        install_packages
        echo
    ;;
    export )
        echo -e "########## Exporting OpenDomoOS to $2 ##########"
        create_image
        export_to_$2
        echo
    ;;
esac
