#!/bin/bash

# Versions, names and packages
ARCH="$2"
ODPKG="odcommon odcgi"
ODVER="2.2.0"
RPKGS="build-essential make gcc cpp libncurses5-dev g++ bison flex gettext texinfo libjpeg8-dev libssl-dev \
          libconfig-dev libsqlite3-dev libusb-dev debhelper devscripts bc"

# Files and directories
FUNCDIR=files/scripts
TEMPDIR=tmp
LOGSDIR=logs
ISOFILES=files/isofiles
RPIFILES=files/rpifiles
MOUNTDIR=mnt
ODPKGDIR=../src
ROOTFSDIR=$TEMPDIR/rootfs.$ARCH
ROOTSTDIR=$TEMPDIR/rootstrap.$ARCH
TARGETDIR=$TEMPDIR/image.$ARCH
EXPORTDIR=exports
IMAGESDIR=$TARGETDIR/images
ROOTFSIMG=$IMAGESDIR/rootfs.img

# Downloads
if [ "$ARCH" != "i386" ]; then
	ROOTFSURL="https://www.dropbox.com/s/ynnn5zo5xpx561i/rootfs.arm.tar.xz"
        ROOTFSPKG="rootfs.arm.tar.xz"
        INITRDIMG=$ROOTFSDIR/boot/initrd.img-3.12-1.bpo.1-486
        KERNELIMG=$ROOTFSDIR/boot/vmlinuz-3.12-1.bpo.1-486
        ODPKGURLS="https://www.dropbox.com/s/phd6c7venpwm6d5/odcgi_2.1.4_armhf.deb \
                   https://www.dropbox.com/s/q64f8ux6voa0eb4/odcommon_2.1.4_armhf.deb"
else
	ROOTFSURL="https://www.dropbox.com/s/95nbpmue86r8t1n/rootfs.i386.tar.xz"
        ROOTFSPKG="rootfs.i386.tar.xz"
        INITRDIMG=$ROOTFSDIR/boot/initrd.img-3.12-0.bpo.1-486
        KERNELIMG=$ROOTFSDIR/boot/vmlinuz-3.12-0.bpo.1-486
        ODPKGURLS="https://www.dropbox.com/s/r0sdsf69df8vta1/odcgi_2.1.4_i386.deb \
                   https://www.dropbox.com/s/mqp6rb8dgdsdab5/odcommon_2.1.4_i386.deb"
fi

# Colors and visual effects
ERRO='\e[0;31m'; INFO='\e[1;34m' ; WARN='\e[0;33m' ; OMIT='\e[1;33m'; DONE='\e[1;32m'; NORL='\e[0m'

# Commands
if test -x /usr/bin/linux32; then
    CHROOT="linux32 chroot"
else
    CHROOT="chroot"
fi
