#! /bin/sh

echo "Configuring opendomo services ..."
insserv odchstates.sh  2>/dev/null
insserv opendomo-apt 2>/dev/null
insserv ntpdate 2>/dev/null

# Create links and wrapper scripts
echo "Creating opendomo configuration ..."
ln -fs /usr/local/opendomo/services/syscript/logEvent.sh /usr/bin/logevent
su -c /usr/bin/createwrappers.sh admin &>/dev/null
/usr/bin/manage_conf.sh copy &>/dev/null

# Modify files and create new initramfs image
echo "aufs" >> /etc/initramfs-tools/modules
/usr/sbin/update-initramfs -u
